default_platform(:ios)

platform :ios do
  lane :devices do
    register_devices(devices_file: "./fastlane/devices.txt")
    match(type: "adhoc", force_for_new_devices: true)
  end

  lane :build_ipa do
    desc "Build ad-hoc ipa (CI)"

    setup_ci
    commit = last_git_commit

    sync_code_signing(
      type: "adhoc",
      readonly: true
    )

    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",

      export_options: {
        method: "ad-hoc",
        manifest: {
          appURL: "https://storage.googleapis.com/flutterttdemo/#{commit[:commit_hash]}/ipa/Runner.ipa",
          displayImageURL: "https://github.com/daohoangson/flutter-tinhte_demo/raw/master/ios/fastlane/logo_57.png",
          fullSizeImageURL: "https://github.com/daohoangson/flutter-tinhte_demo/raw/master/ios/fastlane/logo_512.png"
        }
      },
      output_directory: "../build/app/outputs/ipa/release"
    )
  end

  lane :upload_beta do
    desc "Upload a beta build to TestFlight"

    setup_ci
    sync_code_signing(
      type: "appstore",
      readonly: true
    )

    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: 'app-store',
      xcargs: "PROVISIONING_PROFILE_SPECIFIER='match AppStore com.daohoangson.flutterttdemo'"
    )

    upload_to_testflight(
      api_key_path: "fastlane/4TV2PTBPVG.json"
      distribute_external: true,
      groups: "Public group"
    )
  end
end
