default_platform(:android)

platform :android do
  lane :upload_beta do
    desc "Upload a beta build to Google Play"
    upload_to_play_store(
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      skip_upload_images: true,
      skip_upload_metadata: true,
      skip_upload_screenshots: true,
      track: 'beta'
    )
  end
end
