default_platform(:android)

platform :android do
  lane :beta do
    desc "Deploy a new beta to Google Play"

    upload_to_play_store(
      track: 'beta',
      aab: '../build/app/outputs/bundle/release/app.aab',
      skip_upload_screenshots: true,
      skip_upload_images: true
    )
  end
end
