name: the_api_test

environment:
  sdk: ">=2.18.4 <4.0.0"

dependencies:
  archive: ^3.3.7
  file: ^6.0.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  http: ^1.1.0
  mocktail: ^1.0.0
  path: ^1.8.3
  provider: ^6.0.5
  the_api:
    path: ../api

dev_dependencies:
  flutter_lints: ^2.0.0
