on: push
name: Android APK
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    env:
      GCS_BUCKET: flutterttdemo

    steps:
    - uses: actions/checkout@v1
    - run: git submodule update --init --recursive
    - name: Unlock git-crypt
      uses: sliteteam/github-action-git-crypt-unlock@1.0.2
      env:
        GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
    - name: Extract Flutter version from pubspec.yaml
      id: yq
      run: |
        set -e

        # https://github.com/mikefarah/yq/issues/418
        wget -O /tmp/yq https://github.com/mikefarah/yq/releases/download/3.3.2/yq_linux_amd64
        chmod +x /tmp/yq
        _flutterVersion=$( /tmp/yq read pubspec.yaml environment.flutter )
        echo "::set-output name=FLUTTER_VERSION::$_flutterVersion"

    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: ${{ steps.yq.outputs.FLUTTER_VERSION }}

    - run: flutter pub get
    - run: flutter build apk --split-per-abi

    - name: Create a GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/release/*.apk"
        token: ${{ secrets.TOKEN }}

    - name: Setup gsutil
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_UPLOADER_SA_KEY }}
    - run: gsutil cp build/app/outputs/apk/release/*.apk gs://${GCS_BUCKET}/${GITHUB_SHA}/apks

    - name: Prepare APKs markdown
      id: comment
      run: |
        set -e

        _apksMarkdown=$( \
          ls -d build/app/outputs/apk/release/*.apk \
          | xargs -n 1 basename \
          | xargs -n 1 -I {} printf -- " [%s](https://storage.cloud.google.com/${GCS_BUCKET}/${GITHUB_SHA}/apks/%s)" {} {} \
        )
        echo "::set-output name=APKS_MARKDOWN::$_apksMarkdown"
    - name: Post GitHub comment
      uses: unsplash/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: "Built APKs:${{ steps.comment.outputs.APKS_MARKDOWN }}"
