on: push
name: Android APK
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: textbook/git-checkout-submodule-action@master
    - name: Unlock git-crypt
      uses: sliteteam/github-action-git-crypt-unlock@1.0.2
      env:
        GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
    - name: Extract Flutter version from pubspec.yaml
      id: yq
      run: |
        set -e

        # https://github.com/mikefarah/yq/issues/418
        wget -O /tmp/yq https://github.com/mikefarah/yq/releases/download/3.3.2/yq_linux_amd64
        chmod +x /tmp/yq
        _flutterVersion=$( /tmp/yq read pubspec.yaml environment.flutter )
        echo "::set-output name=FLUTTER_VERSION::$_flutterVersion"

    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: ${{ steps.yq.outputs.FLUTTER_VERSION }}

    - run: flutter pub get

    - name: Build splitted APKs
      if: startsWith(github.ref, 'refs/tags/')
      run: flutter build apk --split-per-abi
    - name: Create a GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/release/*.apk"
        token: ${{ secrets.TOKEN }}

    - name: Build fat APK
      if: startsWith(github.ref, 'refs/tags/') != true
      run: flutter build apk
    - uses: actions/upload-artifact@v2
      if: startsWith(github.ref, 'refs/tags/') != true
      with:
        name: app-release.apk
        path: build/app/outputs/apk/release/app-release.apk
