on: push
name: Cloud Functions for Firebase
jobs:
  deploy:
    if: startsWith(github.ref, 'refs/heads/firebase/functions') || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: firebase/functions
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('firebase/functions/package-lock.json') }}
          restore-keys: |
            npm-

      - run: npm ci
      - run: npm run deploy -- --token ${{ secrets.FIREBASE_TOKEN }}

      - name: Upload npm logs
        uses: actions/upload-artifact@v2
        with:
          name: npm-logs
          path: "~/.npm/_logs/**/*"
