name: Cloud Functions for Firebase
on:
  push:
    paths: 
      - .github/workflows/firebase_functions.yml
      - 'firebase/functions/**'

jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/master' || contains(github.ref, 'gcf') }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: firebase/functions
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('firebase/functions/package-lock.json') }}
          restore-keys: |
            npm-

      - run: npm install --global firebase-tools
      - run: npm ci
      - run: npm run deploy -- --token ${{ secrets.FIREBASE_TOKEN }}

      - name: Upload npm logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: npm-logs
          path: "~/.npm/_logs/**/*"
