on: push
name: Cloud Functions for Firebase
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: firebase/functions
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('firebase/functions/package-lock.json') }}
          restore-keys: |
            npm-
      - run: npm ci
      - run: npm run lint
      - run: npm run build

  deploy:
    if: startsWith(github.ref, 'refs/heads/firebase/functions') || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: firebase
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    
