name: Release
on:
  push:

jobs:
  upload_to_play_store:
    # if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Prepare repo
        run: bash ./.github/workflows/prepare.sh

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - name: Prepare packages/api
        run: ./packages/api/tool/build.sh
      - run: flutter pub get
      - name: Run flutter build appbundle
        run: |
          set -e

          flutter build appbundle
          ( cd ios && fastlane upload_beta )

  upload_to_testflight:
    # if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Prepare repo
        run: bash ./.github/workflows/prepare.sh

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - name: Prepare packages/api
        run: ./packages/api/tool/build.sh
      - run: flutter pub get
      - name: Run flutter build ios
        run: |
          set -e

          flutter build ios || true
          ( cd ios && fastlane upload_beta )
