on: push
name: npm
jobs:
  build:
    name: firebase/functions
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: firebase/functions
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('firebase/functions/package-lock.json') }}
          restore-keys: |
            npm-
      - run: npm ci
      - run: npm run lint
      - run: npm run build
